name: Publish Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to ACR
      uses: docker/login-action@v3
      with:
        registry: cad7ef105d70acr.azurecr.io
        username: ${{ secrets.ALBUMAPI_REGISTRY_USERNAME }}
        password: ${{ secrets.ALBUMAPI_REGISTRY_PASSWORD}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: . # Use path context instead of default git context
        file: ./src/Dockerfile # What is the image build config
        platforms: linux/amd64 # Explicitly define the image architecture(s)
        push: true # Push the image to registry
        provenance: mode=min # By default SLSA mode=min
        sbom: false # Generate SBOM
        tags: cad7ef105d70acr.azurecr.io/containerapps-albumapi-csharp:latest,cad7ef105d70acr.azurecr.io/containerapps-albumapi-csharp:${{ github.sha }}
